# swaggerバージョン宣言
swagger: "2.0"

# 基本情報
info:
  # バージョン表記
  version: 0.0.1
  # タイトル
  title: mailSlurp
  # 説明
  description: |
    - APIでメールボックスを作成・削除でき、受け取ったメールを読むことができる
# リクエスト方式
schemes:
  - http
# ホスト
host: localhost:8888
# 基底パス
basePath: /v1/api/
# タグ定義
tags:
  - name: "Mailbox"
    description: メールボックス
    externalDocs:
      description: "メールボックスのCRUD"
      url: "http://localhost:8080/"
  - name: "Message"
    description: メッセージ
    externalDocs:
      description: "メッセージの取得"
      url: "http://localhost:8080/"
# エンドポイント
paths:
  /mailboxes:
    get:
      summary:
        メールボックス一覧を取得
      tags:
        - Mailbox
      responses:
        200:
          description: OK
          schema:
            type: array
            example: 
              {
                mailboxes: [
                  {
                    mailboxId: D3046B74-8C60-44CE-BFE1-DE2A81098570, 
                    email: D3046B74-8C60-44CE-BFE1-DE2A81098570@catbot.club,
                    link: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/D3046B74-8C60-44CE-BFE1-DE2A81098570
                  },
                  {
                    mailboxId: B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006, 
                    email: B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006@catbot.club,
                    link: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006
                  },
                ]
              }
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }
    post:
      summary:
        メールボックスの作成
      tags: 
        - Mailbox
      responses:
        201:
          description: created
          schema:
            type: array
            example:
              {
                mailboxId: D3046B74-8C60-44CE-BFE1-DE2A81098570, 
                email: D3046B74-8C60-44CE-BFE1-DE2A81098570@catbot.club,
                link: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/D3046B74-8C60-44CE-BFE1-DE2A81098570
              }
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }
            
  /mailboxes/{mailboxId}:
    get:
      summary: 
        メールボックスの詳細を取得
      tags:
        - Mailbox
      parameters:
        - name: mailboxId
          in: header
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              mailboxId:
                type: string
                example: B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006
              email:
                type: string
                example: B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006@catbot.club
              link:
                type: string
                example: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/D3046B74-8C60-44CE-BFE1-DE2A81098570
        404:
          description: Bad Request
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Specified mailbox is not found.
                }
              }
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }


    delete:
      summary:
        指定したメールボックスの削除
      tags:
        - Mailbox
      produces:
        - application/x-www-form-urlencoded
      consumes:
        - application/text/plain
      responses:
        204:
          description: ok
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        404:
          description: Not Found
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Specified mailbox is not found.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }
      parameters:
        - name: mailboxId
          in: header
          type: string
          required: true
  /mailboxes/{mailboxId}/messages:
    get:
      summary:
        メッセージ一覧を取得
      tags:
        - Message
      responses:
        200:
          description: OK
          schema:
            type: array
            example: 
              {
                mailboxes: [
                  {
                    messageId: 773482BC-1ECF-4C2F-9FB9-F2D0C1C8E7180, 
                    receivedAt: Sat, 07 Aug 2021 17:01:43 +0900,
                    link: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/D3046B74-8C60-44CE-BFE1-DE2A81098570/773482BC-1ECF-4C2F-9FB9-F2D0C1C8E7180
                  },
                  {
                    messageId: 53A122EF-58A8-420C-925C-BDC66C2FF2AD, 
                    receivedAt: Sat, 07 Aug 2021 17:02:05 +0900,
                    link: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006/message/53A122EF-58A8-420C-925C-BDC66C2FF2AD
                  },
                ]
              }
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        404:
          description: Not Found
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Specified mailbox is not found.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }

  /mailboxes/{mailboxId}/messages/{messageId}:
    get:
      summary: 
        指定したメッセージの詳細を取得
      tags:
        - Message
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              mailboxId:
                type: string
                example: B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006
              email:
                type: string
                example: B76B2170-2EEB-4E14-AFE0-A5D1BD9A9006@catbot.club
              messageId:
                type: string
                example: 773482BC-1ECF-4C2F-9FB9-F2D0C1C8E7180
              message: 
                type: string
                example: "To: test\nFrom: test@ntt.com\n\nHello, World"
              link:
                type: string
                example: https://localhost:8888/users/7EA0085D-05EE-411D-9CBF-562E2888B690/mailboxes/D3046B74-8C60-44CE-BFE1-DE2A81098570/messages/773482BC-1ECF-4C2F-9FB9-F2D0C1C8E7180
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        404:
          description: Not Found
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Specified message is not found.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }
      parameters:
        - name: mailboxId
          in: header
          type: string
          required: true


    delete:
      summary:
        指定したメッセージの削除
      tags:
        - Message
      produces:
        - application/x-www-form-urlencoded
      consumes:
        - application/text/plain
      responses:
        204:
          description: ok
        401:
          description: Unauthorized
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Invalid token.
                }
              }
        404:
          description: Not Found
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Specified message is not found.
                }
              }
        500:
          description: Internal Server Error
          schema:
            type: array
            example: 
              {
                errors: {
                  message:  Internal Server Error.
                }
              }
      parameters:
        - name: messageId
          in: header
          type: string
          required: true